### ISSUE TITLE
PlayerEx Integration [Question]

### ISSUE THREAD

**Issue by Haikiyu** [semper-idem/semperHud#1]
This is a fantastic mod, but I was just wondering about one thing. Is there a way to get the levels shown in the survival hud to refer to a different value such as the player levels found in PlayerEx?

**Comment by semper-idem** [comment]
not yet but that's good suggestion to add in next release

**Comment by Haikiyu** [comment]
Ahh, I see. Thanks anyway, I'm looking forward to any new updates!
